kind: Pod
apiVersion: v1
metadata: 
  name: myvolsecret
spec:
 containers:
  - name: c00
    image: ubuntu
    command: ["/bin/bash","-c","while true;do echo hello-world;sleep 5;done"]
    volumeMounts:
      - name: testsecret
        mountPath: "/tmp/secret"
 volumes:
   - name: testsecret
     secret:
       secretName: mysecret 